### ISSUE TITLE
Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`

### ISSUE THREAD

**Issue by Puupuls** [talut/react-native-wizard#14]
When using on RN 0.62.2 with wizard 2.0.0

```
Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`
in Step (at react-native-wizard/​index.js:75)
```

https://reactnative.dev/blog/2017/02/14/using-native-driver-for-animated

**Comment by kevinpiac** [comment]
A pull request has just been sent to tackle this issue :) 
Hope it'll be accepted soon.

https://github.com/talut/react-native-wizard/pull/18
