### ISSUE TITLE
Style Animated.View through wizard props

### ISSUE THREAD

**Issue by mosleyjr** [talut/react-native-wizard#17]
I was attempting to alter the css of the Animated.View used in wizard to make it "flex: 1". There does not appear to be a way to pass style to the animated view. My workaround was to edit the index.js file with custom css below.

`return <Animated.View style={[style, {flex: 1}]}>{content}</Animated.View>`

Is there a way to add custom css to the animated view? Or can we add a style prop that can be passed?

**Comment by talut** [comment]
Please check new version.
