### ISSUE TITLE
How to stop transition when validating data

### ISSUE THREAD

**Issue by gomac** [talut/react-native-wizard#2]
Hi, I've setup the wizard in my app and found it very useful. However, before allowing the transition from one step to another I need to validate the data entered and STOP the transition to next step if the validation test fails.

Seems simple but I can't figure out how to stop it. I've tried setting active step and goToStep(previous index) but it gets ignored.

I guess I can hide the next button with showNextButton but I don't think it is a good user experience.

**Comment by talut** [comment]
Please update your package v2.0.0
