### ISSUE TITLE
Typescript definitions for public properties: missing?

### ISSUE THREAD

**Issue by superandrew** [talut/react-native-wizard#21]
Hi, when using this wizard I was trying to type the methods to access wizard's properties, such as  wizard.current?.next().

However it's not clear if this wizard has a type to be put on the Ref in a way that gives the component the possibility to see and use its public properties.

Am I missing something or is this something that has to be done on a typescript definition level?

**Comment by talut** [comment]
Hi, sorry for very very late answer. My TS knowledge not enough for this kinda definitions.  Bur README is showing every possible properties. Such as https://github.com/talut/react-native-wizard#reference-functions
